# Generated by Django 2.2.4 on 2019-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knownfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=10)),
                ('institute', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('hometown', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=20)),
                ('mobile_number', models.IntegerField(max_length=15)),
            ],
        ),
    ]
