# Generated by Django 2.2.4 on 2019-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownfaces',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
    ]
