# Generated by Django 2.2.4 on 2019-09-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20190928_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownfaces',
            name='student_image',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
