# Generated by Django 2.2.4 on 2019-10-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='famousfaces',
            name='image',
            field=models.CharField(default=0, max_length=2000),
        ),
        migrations.AlterField(
            model_name='famousfaces',
            name='external_links',
            field=models.CharField(max_length=1000),
        ),
    ]
