# Generated by Django 2.2.4 on 2019-10-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20191008_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='TestForm',
        ),
    ]
