# Generated by Django 2.2.4 on 2019-10-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20191008_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=50)),
                ('image', models.CharField(default=0, max_length=2000)),
                ('dob', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('movies', models.CharField(max_length=5000)),
                ('awards', models.CharField(max_length=500)),
                ('external_links', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='FamousFaces',
        ),
    ]
