# Generated by Django 2.2.4 on 2019-10-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20191013_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Knownfaces',
        ),
    ]
